### ISSUE TITLE
Can Components be turned into case classes?

### ISSUE THREAD

**Issue by francescopellegrini** [gnosly/fluent-sequence#10]
Overriding `toString`, `hasCode`, and `equals` methods kinda looks like reimplementing case classes.

**Comment by gnosly** [comment]
`ViewModelComponentsFactory` applies all  events from the `eventBook`to the components. So components are not simply dto. They have got some logic needed to create the view model. Further not all are immutable.

**Comment by francescopellegrini** [comment]
Ok, thanks.
