### ISSUE TITLE
Change PointMap.toMap return type

### ISSUE THREAD

**Issue by francescopellegrini** [gnosly/fluent-sequence#13]
The current value of `mutable.TreeMap[String, Fixed2dPoint]` is not really used by itself, instead it's always converted into a `Map[String, Fixed2dPoint]`.

I suggest to return `map.toMap` to make it immutable.

**Comment by gnosly** [comment]
Right! I've already tried this refactoring but the code was harder. I've done! 

See [https://github.com/gnosly/fluent-sequence/commit/b5db1545e3f160f9d9ca706d279b8e0d656ac745](https://github.com/gnosly/fluent-sequence/commit/b5db1545e3f160f9d9ca706d279b8e0d656ac745)
